on: 
  - workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ACTION: Destroy infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: oleg1995petrov/andersen-exam-python-infrastructure

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      
      - name: Send telegram notification if success
        uses: appleboy/telegram-action@master
        if: ${{ failure() || success() }} 
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *Repository*: ${{ github.repository }}

            *Action*: ${{ env.ACTION }}
            *Status*: ${{ job.status }}
          format: markdown
          disable_web_page_preview: true
